os: linux
dist: bionic
language: generic
sudo: required
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - wput
      - pxz
services:
  - docker
before_install:
  - docker pull yshalsager/cyanogenmod:latest
before_script:
  - cd $HOME && mkdir twrp
  - wget -q https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.3.1-20200222/MinimalOmniRecovery-twrp-5.1-norepo-20200222.tar.xz
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/the-hardware-lab/twrp_samsung_fortunave3g.git device/samsung/fortunave3g
  - rm -rf bootable/recovery && git clone https://github.com/TeamWin/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
  - rm -rf external/busybox && git clone https://github.com/omnirom/android_external_busybox -b android-9.0 --depth 1 external/busybox
  - rm -rf external/ntfs-3g && git clone https://github.com/omnirom/android_external_ntfs-3g -b android-8.1 --depth 1 external/ntfs-3g
  - rm -rf external/exfat && git clone https://github.com/omnirom/android_external_exfat -b android-8.1 --depth 1 external/exfat
  - rm -rf external/fuse && git clone https://github.com/omnirom/android_external_fuse -b android-8.0 --depth 1 external/fuse
  - ( rm -rf system/vold || true) && git clone https://github.com/omnirom/android_system_vold -b android-5.1 --depth 1 system/vold
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/cmbuild/twrp/:rw,z" yshalsager/cyanogenmod bash << EOF
    sudo apt-get update -qqy
    #sudo apt-get install -qqy --no-install-recommends openjdk-8-jdk-headless
    cd /home/cmbuild/twrp/
    source build/envsetup.sh
    lunch omni_fortunave3g-eng
    mka recoveryimage 1>/dev/null
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - export nowTime=$(date +%Y%m%d-%H%M)
  - cp $HOME/twrp/out/target/product/fortunave3g/recovery.img $HOME/twrp/TWRP-$version-fortunave3g-$nowTime-Unofficial.img
  - cd $HOME/twrp/out/target/product/fortunave3g/system/
  - tar -I pxz -cf $HOME/twrp/extra-system-files-$nowTime.tar.xz *
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GitOAUTHToken
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    branch: master
branches:
  only:
    - master
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
