os: linux
dist: bionic
language: generic
sudo: required
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - repo
before_script:
  - cd $HOME && mkdir twrp
script:
  - cd $HOME/twrp/
  - repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-5.1
  - repo sync
  - git clone https://github.com/the-hardware-lab/twrp_samsung_fortunave3g.git device/samsung/fortunave3g
  - source build/envsetup.sh
  - lunch omni_fortunave3g-eng
  - mka recoveryimage
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GitOAUTHToken
  file_glob: true
  file: $HOME/twrp/out/target/product/fortunave3g/*.img
  on:
    branch: master
branches:
  only:
    - master
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
